#!/usr/bin/env ruby
# Libarian configuration file for __happen__.
#
# Author:: Greg Albrecht <gba@onbeep.com>
# Copyright:: Copyright 2014 OnBeep, Inc.
# License:: Apache License, Version 2.0
#


site 'http://community.opscode.com/api/v1'

cookbook 'apt'

path 'cookbooks'

cookbook 'splunk',
  :git => 'https://github.com/ampledata/cookbook-splunk.git',
  :ref => 'develop'
